### ISSUE TITLE
Abstract Clocks broken link

### ISSUE THREAD

**Issue by TJScalzo** [tholman/tholman.com#1]
In the Abstract Clocks post you link to a web page that explains how to read the clocks. However, for some reason, `tholman.com` is prepended to the url resulting in users being sent to the page [tholman.com/tholman.com/abstract-clocks](tholman.com/tholman.com/abstract-clocks) instead of [tholman.com/abstract-clocks](tholman.com/abstract-clocks).

**Comment by TJScalzo** [comment]
I believe it's because it doesn't have `http://` at the beginning because other posts that link to pages on the site don't have this issue and they have it.

**Comment by tholman** [comment]
Fixed :)
