### ISSUE TITLE
include in opensource-art project?

### ISSUE THREAD

**Issue by vsoch** [tholman/tholman.com#2]
Hey @tholman !

I'm a software engineer at Stanford Research Computing, and actually I'm doing a fun project that brings together a lot of cool technologies (Github, Continuous Integration, deep learning, docker, etc.) to make an "open source gallery." I saw your post on [circle packing](https://generativeartistry.com/tutorials/circle-packing/), and it blew my mind a bit because it's a programmatic way to generate a pattern that my Mom spends inordinate amounts of time to put into some of her works, for example:

![image](https://user-images.githubusercontent.com/814322/44232765-03fb2580-a170-11e8-9089-7b48ae8b667c.png)

I liked the method from your post that I was using it in development of [this project](https://vsoch.github.io/opensource-art/about/), (and on [Github](https://www.github.com/vsoch/opensource-art))

and added it as an entry too --> https://vsoch.github.io/opensource-art/works/tim-holman-circle-packing/

We are entering it into a show for Red Hat (so she can display works in their gallery) and I wanted to see if it would be ok with you to include the work on the actual site? If not, can I use the algorithm to generate a different image? it's definitely more in spirit with the project to have you included, so I hope this might be ok. I'm still working on all the underlying stuffs so expect changes, but looking forward to chatting with you!  I'm really glad I saw your post, because I love that little picture.

**Comment by tholman** [comment]
Ooh yes, absoluely feel free to use it :) ... this definitely isn't the most elegant circle packing that exists, to get things more like your mum's style you would have the circles "push" each other around, until they get a super tight fit, but in this case, works just as well :)

**Comment by vsoch** [comment]
Thank you! :D <3
